//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pep.Web.App_GlobalResources 
{
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Pep.Web.App_GlobalResources.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        internal static string Btn_Add {
            get {
                return ResourceManager.GetString("Btn_Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string Btn_Cancel {
            get {
                return ResourceManager.GetString("Btn_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import Capabilities.
        /// </summary>
        internal static string Btn_CapabilityImport {
            get {
                return ResourceManager.GetString("Btn_CapabilityImport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import Capability Types.
        /// </summary>
        internal static string Btn_CapabilityTypeImport {
            get {
                return ResourceManager.GetString("Btn_CapabilityTypeImport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import Client Sizes.
        /// </summary>
        internal static string Btn_ClientSizeImport {
            get {
                return ResourceManager.GetString("Btn_ClientSizeImport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy.
        /// </summary>
        internal static string Btn_Copy {
            get {
                return ResourceManager.GetString("Btn_Copy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import Crown Jewel Categories.
        /// </summary>
        internal static string Btn_CrownJewelCategoriesImport {
            get {
                return ResourceManager.GetString("Btn_CrownJewelCategoriesImport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        internal static string Btn_Delete {
            get {
                return ResourceManager.GetString("Btn_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        internal static string Btn_Edit {
            get {
                return ResourceManager.GetString("Btn_Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Roles.
        /// </summary>
        internal static string Btn_EditRole {
            get {
                return ResourceManager.GetString("Btn_EditRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Set.
        /// </summary>
        internal static string Btn_EditSet {
            get {
                return ResourceManager.GetString("Btn_EditSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        internal static string Btn_EditTenant {
            get {
                return ResourceManager.GetString("Btn_EditTenant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit User.
        /// </summary>
        internal static string Btn_EditUser {
            get {
                return ResourceManager.GetString("Btn_EditUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import Root Elements.
        /// </summary>
        internal static string Btn_ElementRootImport {
            get {
                return ResourceManager.GetString("Btn_ElementRootImport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import Root Elements Sub Level.
        /// </summary>
        internal static string Btn_ElementRootSubLevelImport {
            get {
                return ResourceManager.GetString("Btn_ElementRootSubLevelImport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import Maturities.
        /// </summary>
        internal static string Btn_FactCapabilityImport {
            get {
                return ResourceManager.GetString("Btn_FactCapabilityImport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import Fact Threats.
        /// </summary>
        internal static string Btn_FactThreatsImport {
            get {
                return ResourceManager.GetString("Btn_FactThreatsImport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go Back.
        /// </summary>
        internal static string Btn_GoBack {
            get {
                return ResourceManager.GetString("Btn_GoBack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import.
        /// </summary>
        internal static string Btn_Import {
            get {
                return ResourceManager.GetString("Btn_Import", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Publish.
        /// </summary>
        internal static string Btn_Publish {
            get {
                return ResourceManager.GetString("Btn_Publish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Purge.
        /// </summary>
        internal static string Btn_Purge {
            get {
                return ResourceManager.GetString("Btn_Purge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh.
        /// </summary>
        internal static string Btn_Refresh {
            get {
                return ResourceManager.GetString("Btn_Refresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register.
        /// </summary>
        internal static string Btn_Register {
            get {
                return ResourceManager.GetString("Btn_Register", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset.
        /// </summary>
        internal static string Btn_Reset {
            get {
                return ResourceManager.GetString("Btn_Reset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set Password.
        /// </summary>
        internal static string Btn_ResetPassword {
            get {
                return ResourceManager.GetString("Btn_ResetPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset Password.
        /// </summary>
        internal static string Btn_ResetPasswordGrid {
            get {
                return ResourceManager.GetString("Btn_ResetPasswordGrid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset All Playground Tenants.
        /// </summary>
        internal static string Btn_ResetPlayGroundTenants {
            get {
                return ResourceManager.GetString("Btn_ResetPlayGroundTenants", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        internal static string Btn_Save {
            get {
                return ResourceManager.GetString("Btn_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save changes.
        /// </summary>
        internal static string Btn_SaveChanges {
            get {
                return ResourceManager.GetString("Btn_SaveChanges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        internal static string Btn_Search {
            get {
                return ResourceManager.GetString("Btn_Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search for benchmarks.
        /// </summary>
        internal static string Btn_SearchBenchmarks {
            get {
                return ResourceManager.GetString("Btn_SearchBenchmarks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import Sources.
        /// </summary>
        internal static string Btn_SourceImport {
            get {
                return ResourceManager.GetString("Btn_SourceImport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test current credentials.
        /// </summary>
        internal static string Btn_TestCredentials {
            get {
                return ResourceManager.GetString("Btn_TestCredentials", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import Threat Actors.
        /// </summary>
        internal static string Btn_ThreatActorsImport {
            get {
                return ResourceManager.GetString("Btn_ThreatActorsImport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import Threat Techniques.
        /// </summary>
        internal static string Btn_ThreatTechniquesImport {
            get {
                return ResourceManager.GetString("Btn_ThreatTechniquesImport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update.
        /// </summary>
        internal static string Btn_Update {
            get {
                return ResourceManager.GetString("Btn_Update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update Roles.
        /// </summary>
        internal static string Btn_UpdateRoles {
            get {
                return ResourceManager.GetString("Btn_UpdateRoles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        internal static string Buttons_Add {
            get {
                return ResourceManager.GetString("Buttons_Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add New.
        /// </summary>
        internal static string Buttons_AddNew {
            get {
                return ResourceManager.GetString("Buttons_AddNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string Buttons_Cancel {
            get {
                return ResourceManager.GetString("Buttons_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        internal static string Buttons_Delete {
            get {
                return ResourceManager.GetString("Buttons_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit selected object.
        /// </summary>
        internal static string Buttons_EditSelected {
            get {
                return ResourceManager.GetString("Buttons_EditSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move down selected object.
        /// </summary>
        internal static string Buttons_MoveDownSelected {
            get {
                return ResourceManager.GetString("Buttons_MoveDownSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move up selected object.
        /// </summary>
        internal static string Buttons_MoveUpSelected {
            get {
                return ResourceManager.GetString("Buttons_MoveUpSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove selected object.
        /// </summary>
        internal static string Buttons_RemoveSelected {
            get {
                return ResourceManager.GetString("Buttons_RemoveSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        internal static string Buttons_Save {
            get {
                return ResourceManager.GetString("Buttons_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go back.
        /// </summary>
        internal static string Button_GoBack {
            get {
                return ResourceManager.GetString("Button_GoBack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Welcome?.
        /// </summary>
        internal static string Columns_WelcomeNotice {
            get {
                return ResourceManager.GetString("Columns_WelcomeNotice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure to perfom this action?.
        /// </summary>
        internal static string ConfirmDelete_DefaultMessage {
            get {
                return ResourceManager.GetString("ConfirmDelete_DefaultMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete confirmation.
        /// </summary>
        internal static string ConfirmDelete_DefaultTitle {
            get {
                return ResourceManager.GetString("ConfirmDelete_DefaultTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to See Terms &amp;amp; Conditions for more information.
        ///            &lt;br /&gt;
        ///            Deloitte refers to one or more of Deloitte Touche Tohmatsu Limited, a UK private company limited by guarantee (&amp;quot;DTTL&amp;quot;),
        ///            its network of member&lt;br /&gt; firms, and their related entities. DTTL and each of its member firms are legally separate and independent entities.
        ///            DTTL (also referred to as&lt;br /&gt;  &amp;quot;Deloitte global&amp;quot;) does not provide services to clients.
        ///            Please see &lt;a href=&quot;ht [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string DeloitteFooter {
            get {
                return ResourceManager.GetString("DeloitteFooter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error has occurred.
        /// </summary>
        internal static string Error_DropzoneAlertMessage {
            get {
                return ResourceManager.GetString("Error_DropzoneAlertMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to \n The file type is not correct. Please select a valid csv file..
        /// </summary>
        internal static string Error_DropzoneFileTypeIncorrect {
            get {
                return ResourceManager.GetString("Error_DropzoneFileTypeIncorrect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The following messages have been generated:.
        /// </summary>
        internal static string Error_DropzoneTitle {
            get {
                return ResourceManager.GetString("Error_DropzoneTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A general error has ocurred..
        /// </summary>
        internal static string Error_General {
            get {
                return ResourceManager.GetString("Error_General", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oops!.
        /// </summary>
        internal static string Error_GeneralTitle {
            get {
                return ResourceManager.GetString("Error_GeneralTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If the problem persists, please contact.
        /// </summary>
        internal static string Error_Generic {
            get {
                return ResourceManager.GetString("Error_Generic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An exception error has occurred.
        /// </summary>
        internal static string Error_GenericTitle {
            get {
                return ResourceManager.GetString("Error_GenericTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to nremt@nremt.com.
        /// </summary>
        internal static string Error_Mail {
            get {
                return ResourceManager.GetString("Error_Mail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to National Regitry of Emergency Medical Technicians.
        /// </summary>
        internal static string Error_MailTitle {
            get {
                return ResourceManager.GetString("Error_MailTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Slashes are not allowed in the name.
        /// </summary>
        internal static string Error_NoSlash {
            get {
                return ResourceManager.GetString("Error_NoSlash", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The object you are looking for was not found. If the problem persists, please contact.
        /// </summary>
        internal static string Error_ObjectNotFound {
            get {
                return ResourceManager.GetString("Error_ObjectNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Object not found.
        /// </summary>
        internal static string Error_ObjectNotFoundAjax {
            get {
                return ResourceManager.GetString("Error_ObjectNotFoundAjax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tenant Playground must be declared with Demo mode.
        /// </summary>
        internal static string Error_PlaygroundAndNotDemoTenant {
            get {
                return ResourceManager.GetString("Error_PlaygroundAndNotDemoTenant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please contact Administrator to provide neccessary access..
        /// </summary>
        internal static string Error_UnAuthorizedMessage {
            get {
                return ResourceManager.GetString("Error_UnAuthorizedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your not Authorized to view this resource.
        /// </summary>
        internal static string Error_UnAuthorizedTitle {
            get {
                return ResourceManager.GetString("Error_UnAuthorizedTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Name and Email must be the same.
        /// </summary>
        internal static string Error_UserNameAndEmailNotMatch {
            get {
                return ResourceManager.GetString("Error_UserNameAndEmailNotMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User that contains &apos;Technical Administrator&apos; role can not delete from this tenant.
        /// </summary>
        internal static string Error_UserRoleTechnicalAdministrator {
            get {
                return ResourceManager.GetString("Error_UserRoleTechnicalAdministrator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The session has been expired. Please login again.
        /// </summary>
        internal static string ExpiredSession {
            get {
                return ResourceManager.GetString("ExpiredSession", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error in data format..
        /// </summary>
        internal static string Ex_DataNotFound {
            get {
                return ResourceManager.GetString("Ex_DataNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your account has not been setup to use this application..
        /// </summary>
        internal static string Forbidden {
            get {
                return ResourceManager.GetString("Forbidden", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A business driven and threat based approach to understand your cyber risk posture..
        /// </summary>
        internal static string Framework_Description {
            get {
                return ResourceManager.GetString("Framework_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NREMT.
        /// </summary>
        internal static string General_ApplicationName {
            get {
                return ResourceManager.GetString("General_ApplicationName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The changes have been cancelled..
        /// </summary>
        internal static string Info_ObjectCanceledChanges {
            get {
                return ResourceManager.GetString("Info_ObjectCanceledChanges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Object created succesfully..
        /// </summary>
        internal static string Info_ObjectCreated {
            get {
                return ResourceManager.GetString("Info_ObjectCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Object deleted successfully..
        /// </summary>
        internal static string Info_ObjectDeleted {
            get {
                return ResourceManager.GetString("Info_ObjectDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Object updated successfully..
        /// </summary>
        internal static string Info_ObjectUpdated {
            get {
                return ResourceManager.GetString("Info_ObjectUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set models updated successfully.
        /// </summary>
        internal static string Info_SetUpdated {
            get {
                return ResourceManager.GetString("Info_SetUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Advanced Search.
        /// </summary>
        internal static string Label_AdvSearch {
            get {
                return ResourceManager.GetString("Label_AdvSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Crown Jewel Categories.
        /// </summary>
        internal static string Label_AssetCategories {
            get {
                return ResourceManager.GetString("Label_AssetCategories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Crown Jewel Category.
        /// </summary>
        internal static string Label_AssetCategory {
            get {
                return ResourceManager.GetString("Label_AssetCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Background Color.
        /// </summary>
        internal static string Label_BackgroundColor {
            get {
                return ResourceManager.GetString("Label_BackgroundColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code.
        /// </summary>
        internal static string Label_Code {
            get {
                return ResourceManager.GetString("Label_Code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm new password.
        /// </summary>
        internal static string Label_ConfirmNewPassword {
            get {
                return ResourceManager.GetString("Label_ConfirmNewPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm password.
        /// </summary>
        internal static string Label_ConfirmPassword {
            get {
                return ResourceManager.GetString("Label_ConfirmPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connection String.
        /// </summary>
        internal static string Label_ConnectionString {
            get {
                return ResourceManager.GetString("Label_ConnectionString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create new source.
        /// </summary>
        internal static string Label_CreateNewSource {
            get {
                return ResourceManager.GetString("Label_CreateNewSource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create new tenant.
        /// </summary>
        internal static string Label_CreateNewTenant {
            get {
                return ResourceManager.GetString("Label_CreateNewTenant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create New Tenant License.
        /// </summary>
        internal static string Label_CreateNewTenantLicense {
            get {
                return ResourceManager.GetString("Label_CreateNewTenantLicense", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Culture.
        /// </summary>
        internal static string Label_Culture {
            get {
                return ResourceManager.GetString("Label_Culture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get log messages from:.
        /// </summary>
        internal static string Label_DateLogs {
            get {
                return ResourceManager.GetString("Label_DateLogs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        internal static string Label_Description {
            get {
                return ResourceManager.GetString("Label_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disabled?.
        /// </summary>
        internal static string Label_Disabled {
            get {
                return ResourceManager.GetString("Label_Disabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accept the disclaimer?.
        /// </summary>
        internal static string Label_DisclaimerAccepted {
            get {
                return ResourceManager.GetString("Label_DisclaimerAccepted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download All Open Questions.
        /// </summary>
        internal static string Label_Download_All_OpenQuestionsXML {
            get {
                return ResourceManager.GetString("Label_Download_All_OpenQuestionsXML", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download All Statements.
        /// </summary>
        internal static string Label_Download_All_StatementsXML {
            get {
                return ResourceManager.GetString("Label_Download_All_StatementsXML", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download Open Questions for the selected Capability.
        /// </summary>
        internal static string Label_Download_OpenQuestionsXML {
            get {
                return ResourceManager.GetString("Label_Download_OpenQuestionsXML", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download Statement Answers.
        /// </summary>
        internal static string Label_Download_QuestionValuesXML {
            get {
                return ResourceManager.GetString("Label_Download_QuestionValuesXML", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download Statements for the selected Capability.
        /// </summary>
        internal static string Label_Download_StatementsXML {
            get {
                return ResourceManager.GetString("Label_Download_StatementsXML", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Draft.
        /// </summary>
        internal static string Label_Draft {
            get {
                return ResourceManager.GetString("Label_Draft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload up to 10MB. Attach a file of csv type..
        /// </summary>
        internal static string Label_DropzoneSubtitle {
            get {
                return ResourceManager.GetString("Label_DropzoneSubtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attach new file.
        /// </summary>
        internal static string Label_DropzoneTitle {
            get {
                return ResourceManager.GetString("Label_DropzoneTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit account information.
        /// </summary>
        internal static string Label_EditAccountInfo {
            get {
                return ResourceManager.GetString("Label_EditAccountInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        internal static string Label_Email {
            get {
                return ResourceManager.GetString("Label_Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter new password.
        /// </summary>
        internal static string Label_EnterNewPassword {
            get {
                return ResourceManager.GetString("Label_EnterNewPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expiration Date.
        /// </summary>
        internal static string Label_ExpirationDate {
            get {
                return ResourceManager.GetString("Label_ExpirationDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File.
        /// </summary>
        internal static string Label_File {
            get {
                return ResourceManager.GetString("Label_File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First Name.
        /// </summary>
        internal static string Label_FirstName {
            get {
                return ResourceManager.GetString("Label_FirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go To Manage Users.
        /// </summary>
        internal static string Label_GoToManageUsers {
            get {
                return ResourceManager.GetString("Label_GoToManageUsers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to For Demo?.
        /// </summary>
        internal static string Label_IsForDemo {
            get {
                return ResourceManager.GetString("Label_IsForDemo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to For Playground?.
        /// </summary>
        internal static string Label_IsForPlayground {
            get {
                return ResourceManager.GetString("Label_IsForPlayground", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to For Training?.
        /// </summary>
        internal static string Label_IsForTraining {
            get {
                return ResourceManager.GetString("Label_IsForTraining", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Free text.
        /// </summary>
        internal static string Label_IsFreeText {
            get {
                return ResourceManager.GetString("Label_IsFreeText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is mandatory.
        /// </summary>
        internal static string Label_IsMandatory {
            get {
                return ResourceManager.GetString("Label_IsMandatory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is Playground?.
        /// </summary>
        internal static string Label_IsPlayground {
            get {
                return ResourceManager.GetString("Label_IsPlayground", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Name.
        /// </summary>
        internal static string Label_LastName {
            get {
                return ResourceManager.GetString("Label_LastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Level.
        /// </summary>
        internal static string Label_Level {
            get {
                return ResourceManager.GetString("Label_Level", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to License.
        /// </summary>
        internal static string Label_License {
            get {
                return ResourceManager.GetString("Label_License", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading.
        /// </summary>
        internal static string Label_Load {
            get {
                return ResourceManager.GetString("Label_Load", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Multiple Selection.
        /// </summary>
        internal static string Label_MultipleSelection {
            get {
                return ResourceManager.GetString("Label_MultipleSelection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string Label_Name {
            get {
                return ResourceManager.GetString("Label_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New assword.
        /// </summary>
        internal static string Label_NewPassword {
            get {
                return ResourceManager.GetString("Label_NewPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No data.
        /// </summary>
        internal static string Label_NoData {
            get {
                return ResourceManager.GetString("Label_NoData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open-ended questions.
        /// </summary>
        internal static string Label_OpenQuestionsTab {
            get {
                return ResourceManager.GetString("Label_OpenQuestionsTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Option.
        /// </summary>
        internal static string Label_Option {
            get {
                return ResourceManager.GetString("Label_Option", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Option description.
        /// </summary>
        internal static string Label_OptionDescription {
            get {
                return ResourceManager.GetString("Label_OptionDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        internal static string Label_Password {
            get {
                return ResourceManager.GetString("Label_Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Published.
        /// </summary>
        internal static string Label_Published {
            get {
                return ResourceManager.GetString("Label_Published", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Read Only.
        /// </summary>
        internal static string Label_ReadOnly {
            get {
                return ResourceManager.GetString("Label_ReadOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh Tokens.
        /// </summary>
        internal static string Label_RefreshTokens {
            get {
                return ResourceManager.GetString("Label_RefreshTokens", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registered Roles.
        /// </summary>
        internal static string Label_RegisteredRoles {
            get {
                return ResourceManager.GetString("Label_RegisteredRoles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registered Sets.
        /// </summary>
        internal static string Label_RegisteredSet {
            get {
                return ResourceManager.GetString("Label_RegisteredSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registered tenants.
        /// </summary>
        internal static string Label_RegisteredTenants {
            get {
                return ResourceManager.GetString("Label_RegisteredTenants", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registered Users.
        /// </summary>
        internal static string Label_RegisteredUsers {
            get {
                return ResourceManager.GetString("Label_RegisteredUsers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create new account.
        /// </summary>
        internal static string Label_RegisterNewAccount {
            get {
                return ResourceManager.GetString("Label_RegisterNewAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register new Set.
        /// </summary>
        internal static string Label_RegisterNewSet {
            get {
                return ResourceManager.GetString("Label_RegisterNewSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Source.
        /// </summary>
        internal static string Label_Source {
            get {
                return ResourceManager.GetString("Label_Source", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Starting Date.
        /// </summary>
        internal static string Label_StartingDate {
            get {
                return ResourceManager.GetString("Label_StartingDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sub-capability.
        /// </summary>
        internal static string Label_SubCapability {
            get {
                return ResourceManager.GetString("Label_SubCapability", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tenant Name.
        /// </summary>
        internal static string Label_TenantName {
            get {
                return ResourceManager.GetString("Label_TenantName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tenant User.
        /// </summary>
        internal static string Label_TenantUser {
            get {
                return ResourceManager.GetString("Label_TenantUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test CSF Connection.
        /// </summary>
        internal static string Label_TestCSFConnection {
            get {
                return ResourceManager.GetString("Label_TestCSFConnection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Threat Actor.
        /// </summary>
        internal static string Label_ThreatActor {
            get {
                return ResourceManager.GetString("Label_ThreatActor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Threat Technique.
        /// </summary>
        internal static string Label_ThreatTechnique {
            get {
                return ResourceManager.GetString("Label_ThreatTechnique", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload.
        /// </summary>
        internal static string Label_Upload {
            get {
                return ResourceManager.GetString("Label_Upload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use Lowest Score.
        /// </summary>
        internal static string Label_UseLowestScore {
            get {
                return ResourceManager.GetString("Label_UseLowestScore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Name.
        /// </summary>
        internal static string Label_UserName {
            get {
                return ResourceManager.GetString("Label_UserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Roles.
        /// </summary>
        internal static string Label_UserRoles {
            get {
                return ResourceManager.GetString("Label_UserRoles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Main section.
        /// </summary>
        internal static string MainHomeSection {
            get {
                return ResourceManager.GetString("MainHomeSection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The {0} you are trying to delete could have related entities linked to it. If you delete it, the related entities will be removed too.\nAre you sure you want to remove this {0}?.
        /// </summary>
        internal static string Message_ConfimationDeleteMessage {
            get {
                return ResourceManager.GetString("Message_ConfimationDeleteMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete the selected tenant user?.
        /// </summary>
        internal static string Message_ConfimationDeleteMessageTenantUser {
            get {
                return ResourceManager.GetString("Message_ConfimationDeleteMessageTenantUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to remove the selected element?.
        /// </summary>
        internal static string Message_ConfimationDeteleMessage {
            get {
                return ResourceManager.GetString("Message_ConfimationDeteleMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to remove the selected {0}?.
        /// </summary>
        internal static string Message_ConfimationDeteleMessageCatalog {
            get {
                return ResourceManager.GetString("Message_ConfimationDeteleMessageCatalog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The {0} you are trying to delete has related entities linked to it. If you delete it, the related entities will be removed too.\nAre you sure you want to remove this {0}?.
        /// </summary>
        internal static string Message_ConfimationDeteleMessageRelatedEntities {
            get {
                return ResourceManager.GetString("Message_ConfimationDeteleMessageRelatedEntities", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete confirmation.
        /// </summary>
        internal static string Message_ConfirmationDeleteTitle {
            get {
                return ResourceManager.GetString("Message_ConfirmationDeleteTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirmation.
        /// </summary>
        internal static string Message_ConfirmationTitle {
            get {
                return ResourceManager.GetString("Message_ConfirmationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connection succesfully stablished..
        /// </summary>
        internal static string Message_ConnecctionSuccesfull {
            get {
                return ResourceManager.GetString("Message_ConnecctionSuccesfull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drop files here or click to upload..
        /// </summary>
        internal static string Message_DropzoneDefaultMessage {
            get {
                return ResourceManager.GetString("Message_DropzoneDefaultMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The process has deleted {0} records..
        /// </summary>
        internal static string Message_ImportDeleteData {
            get {
                return ResourceManager.GetString("Message_ImportDeleteData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The file has been successfully imported.
        /// </summary>
        internal static string Message_ImportFactCapabilitySuccess {
            get {
                return ResourceManager.GetString("Message_ImportFactCapabilitySuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The process has inserted {0} records..
        /// </summary>
        internal static string Message_ImportInsertData {
            get {
                return ResourceManager.GetString("Message_ImportInsertData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The process has updated {0} records..
        /// </summary>
        internal static string Message_ImportUpdateData {
            get {
                return ResourceManager.GetString("Message_ImportUpdateData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It is not allowed to edit the existing data of a client..
        /// </summary>
        internal static string Message_NoAllowEditDataOfAClient {
            get {
                return ResourceManager.GetString("Message_NoAllowEditDataOfAClient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No benchmark information was found.
        /// </summary>
        internal static string Message_NoBenchmarkInformation {
            get {
                return ResourceManager.GetString("Message_NoBenchmarkInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Changes have been saved successfully..
        /// </summary>
        internal static string Message_SavedChanges {
            get {
                return ResourceManager.GetString("Message_SavedChanges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please, select an element root for sub element {0}..
        /// </summary>
        internal static string Message_Warning_ElementRoot {
            get {
                return ResourceManager.GetString("Message_Warning_ElementRoot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please, select a sub element root for capability {0}..
        /// </summary>
        internal static string Message_Warning_ElementRootSubLevel {
            get {
                return ResourceManager.GetString("Message_Warning_ElementRootSubLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        internal static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to For immediate assistance or questions, please contact.
        /// </summary>
        internal static string NotAllowToViewThisPage {
            get {
                return ResourceManager.GetString("NotAllowToViewThisPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This page could not be found. If the problem persists, please contact.
        /// </summary>
        internal static string NotFound {
            get {
                return ResourceManager.GetString("NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Object edited.
        /// </summary>
        internal static string ObjectEditedText {
            get {
                return ResourceManager.GetString("ObjectEditedText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ok.
        /// </summary>
        internal static string Ok {
            get {
                return ResourceManager.GetString("Ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please, select a value.
        /// </summary>
        internal static string SelectAValue {
            get {
                return ResourceManager.GetString("SelectAValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sets.
        /// </summary>
        internal static string SetsSection {
            get {
                return ResourceManager.GetString("SetsSection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string String1 {
            get {
                return ResourceManager.GetString("String1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string String11 {
            get {
                return ResourceManager.GetString("String11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Radia Connections.
        /// </summary>
        internal static string Tab_Connections {
            get {
                return ResourceManager.GetString("Tab_Connections", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Link tenants.
        /// </summary>
        internal static string Tab_LinkTenantsToUsers {
            get {
                return ResourceManager.GetString("Tab_LinkTenantsToUsers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register New.
        /// </summary>
        internal static string Tab_RegisterNew {
            get {
                return ResourceManager.GetString("Tab_RegisterNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register New Tenant.
        /// </summary>
        internal static string Tab_RegisterNewTenant {
            get {
                return ResourceManager.GetString("Tab_RegisterNewTenant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register New User.
        /// </summary>
        internal static string Tab_RegisterNewUser {
            get {
                return ResourceManager.GetString("Tab_RegisterNewUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Roles.
        /// </summary>
        internal static string Tab_Roles {
            get {
                return ResourceManager.GetString("Tab_Roles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sets.
        /// </summary>
        internal static string Tab_Sets {
            get {
                return ResourceManager.GetString("Tab_Sets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tenants.
        /// </summary>
        internal static string Tab_Tenants {
            get {
                return ResourceManager.GetString("Tab_Tenants", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tokens.
        /// </summary>
        internal static string Tab_Tokens {
            get {
                return ResourceManager.GetString("Tab_Tokens", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Users.
        /// </summary>
        internal static string Tab_Users {
            get {
                return ResourceManager.GetString("Tab_Users", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tenants.
        /// </summary>
        internal static string TenantSection {
            get {
                return ResourceManager.GetString("TenantSection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tenant user management.
        /// </summary>
        internal static string TenantUser_Title_UserManagement {
            get {
                return ResourceManager.GetString("TenantUser_Title_UserManagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Users.
        /// </summary>
        internal static string TenantUser_Users {
            get {
                return ResourceManager.GetString("TenantUser_Users", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage the user for the tenants.
        /// </summary>
        internal static string TenantUser_UsersDescription {
            get {
                return ResourceManager.GetString("TenantUser_UsersDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User.
        /// </summary>
        internal static string TenantUser_UsersSection {
            get {
                return ResourceManager.GetString("TenantUser_UsersSection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Benchmark.
        /// </summary>
        internal static string Tiles_Benchmark {
            get {
                return ResourceManager.GetString("Tiles_Benchmark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View and interact with all loaded benchmark information..
        /// </summary>
        internal static string Tiles_BenchmarkDescription {
            get {
                return ResourceManager.GetString("Tiles_BenchmarkDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View and interact with all loaded content information..
        /// </summary>
        internal static string Tiles_CatalogDescription {
            get {
                return ResourceManager.GetString("Tiles_CatalogDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MainDescription.
        /// </summary>
        internal static string Tiles_MainDescription {
            get {
                return ResourceManager.GetString("Tiles_MainDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage the users of the benchmark application..
        /// </summary>
        internal static string Tiles_UsersDescription {
            get {
                return ResourceManager.GetString("Tiles_UsersDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage Sets.
        /// </summary>
        internal static string Titles_SetsDescription {
            get {
                return ResourceManager.GetString("Titles_SetsDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tenant management.
        /// </summary>
        internal static string Titles_TenantDescription {
            get {
                return ResourceManager.GetString("Titles_TenantDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configuration.
        /// </summary>
        internal static string Title_Configuration {
            get {
                return ResourceManager.GetString("Title_Configuration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import.
        /// </summary>
        internal static string Title_ImportWindow {
            get {
                return ResourceManager.GetString("Title_ImportWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set Management.
        /// </summary>
        internal static string Title_SetManagement {
            get {
                return ResourceManager.GetString("Title_SetManagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Content Pack Management.
        /// </summary>
        internal static string Title_SetsModels {
            get {
                return ResourceManager.GetString("Title_SetsModels", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registered CSF Connections to Publish Tenants.
        /// </summary>
        internal static string Title_TenantCnnManagement {
            get {
                return ResourceManager.GetString("Title_TenantCnnManagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tenant Management.
        /// </summary>
        internal static string Title_TenantManagement {
            get {
                return ResourceManager.GetString("Title_TenantManagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Management.
        /// </summary>
        internal static string Title_UserManagement {
            get {
                return ResourceManager.GetString("Title_UserManagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Admin.
        /// </summary>
        internal static string UI_Admin {
            get {
                return ResourceManager.GetString("UI_Admin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact.
        /// </summary>
        internal static string UI_Contact {
            get {
                return ResourceManager.GetString("UI_Contact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        internal static string UI_Edit {
            get {
                return ResourceManager.GetString("UI_Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maturities.
        /// </summary>
        internal static string UI_FactCapability {
            get {
                return ResourceManager.GetString("UI_FactCapability", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Questionnaire answers.
        /// </summary>
        internal static string UI_FactQuestions {
            get {
                return ResourceManager.GetString("UI_FactQuestions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Threat Exposures.
        /// </summary>
        internal static string UI_FactThreats {
            get {
                return ResourceManager.GetString("UI_FactThreats", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help.
        /// </summary>
        internal static string UI_Help {
            get {
                return ResourceManager.GetString("UI_Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        internal static string UI_Home {
            get {
                return ResourceManager.GetString("UI_Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log In.
        /// </summary>
        internal static string UI_LogIn {
            get {
                return ResourceManager.GetString("UI_LogIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log off.
        /// </summary>
        internal static string UI_LogOff {
            get {
                return ResourceManager.GetString("UI_LogOff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log Viewer.
        /// </summary>
        internal static string UI_LogViewer {
            get {
                return ResourceManager.GetString("UI_LogViewer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log Viewer WebApi.
        /// </summary>
        internal static string UI_LogViewerApi {
            get {
                return ResourceManager.GetString("UI_LogViewerApi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Root Elements.
        /// </summary>
        internal static string UI_RootElements {
            get {
                return ResourceManager.GetString("UI_RootElements", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Root Elements Sub Level.
        /// </summary>
        internal static string UI_RootElementsSubLevel {
            get {
                return ResourceManager.GetString("UI_RootElementsSubLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set.
        /// </summary>
        internal static string UI_Set {
            get {
                return ResourceManager.GetString("UI_Set", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sets.
        /// </summary>
        internal static string UI_Sets {
            get {
                return ResourceManager.GetString("UI_Sets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sources.
        /// </summary>
        internal static string UI_Source {
            get {
                return ResourceManager.GetString("UI_Source", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tenants.
        /// </summary>
        internal static string UI_Tenant {
            get {
                return ResourceManager.GetString("UI_Tenant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Users.
        /// </summary>
        internal static string UI_TenantUsers {
            get {
                return ResourceManager.GetString("UI_TenantUsers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nremt.
        /// </summary>
        internal static string UI_TextUnderLogo {
            get {
                return ResourceManager.GetString("UI_TextUnderLogo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Users.
        /// </summary>
        internal static string UI_Users {
            get {
                return ResourceManager.GetString("UI_Users", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Users.
        /// </summary>
        internal static string UsersSection {
            get {
                return ResourceManager.GetString("UsersSection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        internal static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
    }
}
